---
- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest

- name: start the service
  service:
    name: httpd
    state: started

- name: add rule to FW
  firewalld:
    service: http
    permanent: true
    state: enabled
#  notify: restart firewalld